linters:
  enable-all: true
  disable:
    - depguard

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/devem-tech/echo)
  varnamelen:
    ignore-names:
      - x, sb, ok, fn
      - r, w, rw

issues:
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - funlen